### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cds4r** [seven-gram/seven-gram#2]
C:\Users\Admin\Desktop\seven-gram-master\dist>node main.js
================================
 Missing environment variables:
    NODE_ENV: undefined
================================

 Exiting with error code 1 

Не могу разобраться

**Comment by d-kurchenko** [comment]
Пофиксил в 4f86c543feb734168c782c3149de3509e7e53d86. Но будьте осторожны, у бота пока нет настроек и настроить его под себя пока можно только через код. Например вам может не подойти то, что по умолчанию выставлена прокачка карт если соотношение цены прокачки к прибыли меньше чем 1:4000. В будущем добавлю возможность управлять настройками через телеграм.
