### ISSUE TITLE
Help not working 

### ISSUE THREAD

**Issue by painterzeou** [seven-gram/seven-gram#3]
Whatever i do it seems it's not connected

I edited 
.env file 
Like this
API_ID="00000"
API_HASH="73udieiie"

And like this 
NODE_ENV=local
API_ID="00000"
API_HASH="73udieiie"

But nothing happene in my account nothing connected

**Comment by d-kurchenko** [comment]
`API_ID` & `API_HASH` tokens are filled via terminal prompts. May be it happens because you are trying to start it with `npm run pm2:start` command, and pm2 grap process stdin. Try to start app with `npm run start`

**Comment by painterzeou** [comment]
Thanks it worked
But commands not working
.help or .ping

**Comment by d-kurchenko** [comment]
> Thanks it worked
> But commands not working
> .help or .ping 


how did you know it worked? Is there some errors in logs?

**Comment by painterzeou** [comment]
No there's hamster logs and it seems good 
But no commands to respond

**Comment by d-kurchenko** [comment]
commans not working in notes. Try write them in any another chat fhr example `Seven Gram | BOT`

**Comment by painterzeou** [comment]
I did 
I wrote commands in everywhere 😕

**Comment by d-kurchenko** [comment]
> I did 
> I wrote commands in everywhere 😕

Were bot and logs chats created?

**Comment by painterzeou** [comment]
Yes 
And now hamster working logs update with hamster quests

**Comment by d-kurchenko** [comment]
> Yes And now hamster working logs update with hamster quests

Try to change NODE_ENV value to `production` and restart app

**Comment by painterzeou** [comment]
Ok now it worked
But is the hamster the only game

**Comment by d-kurchenko** [comment]
> Ok now it worked But is the hamster the only game

for now, yes
