### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by xaxazic007** [seven-gram/seven-gram#4]
Is there any detailed guide on it? How to run?

**Comment by TELUGUSCRIPTER** [comment]
hi have you finded how to run this?

**Comment by d-kurchenko** [comment]
@TELUGUSCRIPTER, @xaxazic007 Instruction was added in the last update. You can find it in [READ.ME](https://github.com/seven-gram/seven-gram/blob/master/README.md) file
